language: python

sudo: false

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install tox-travis
  - pip install coverage
  - pip install codecov

script:
  - tox

after_success:
  - coverage combine && codecov
