language: python

sudo: false

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

script:
  - python -c 'import nltk; nltk.download("punkt"); nltk.download("averaged_perceptron_tagger"); nltk.download("maxent_ne_chunker"); nltk.download("words")'
  - coverage run -m unittest tests.test_suit
  - coverage report -m

after_success:
  - codecov
